"""empty message

Revision ID: 10d4a6a6b958
Revises: e7688ae9d30b
Create Date: 2020-03-07 15:27:57.866343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10d4a6a6b958'
down_revision = 'e7688ae9d30b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response', sa.Column('pretest_key_status', sa.Text(), nullable=True))
    op.add_column('response', sa.Column('pretest_token', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('response', 'pretest_token')
    op.drop_column('response', 'pretest_key_status')
    # ### end Alembic commands ###
