"""empty message

Revision ID: 4ca12d1b238d
Revises: 10d4a6a6b958
Create Date: 2020-03-19 12:58:11.013704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ca12d1b238d'
down_revision = '10d4a6a6b958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response', sa.Column('post_test_agents', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('response', 'post_test_agents')
    # ### end Alembic commands ###
