"""empty message

Revision ID: 808f75987db1
Revises: fc015c6f4fd5
Create Date: 2020-04-22 12:23:23.842715

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '808f75987db1'
down_revision = 'fc015c6f4fd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('response', 'pretest_reactions2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response', sa.Column('pretest_reactions2', mysql.MEDIUMTEXT(collation='utf8_bin'), nullable=True))
    # ### end Alembic commands ###
