"""empty message

Revision ID: e7688ae9d30b
Revises: a3be18904c27
Create Date: 2020-03-06 18:15:24.156288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7688ae9d30b'
down_revision = 'a3be18904c27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response', sa.Column('pretest_status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('response', 'pretest_status')
    # ### end Alembic commands ###
