"""empty message

Revision ID: f4b8f0c9c12c
Revises: 808f75987db1
Create Date: 2020-04-22 12:28:35.378380

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f4b8f0c9c12c'
down_revision = '808f75987db1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('response', 'post_test_agents',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('response', 'pretest_key_status',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('response', 'pretest_keys',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('response', 'pretest_reactions',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('response', 'pretest_reactions',
               existing_type=mysql.MEDIUMTEXT(),
               type_=mysql.TEXT(collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('response', 'pretest_keys',
               existing_type=sa.Text(),
               type_=mysql.TEXT(collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('response', 'pretest_key_status',
               existing_type=sa.Text(),
               type_=mysql.TEXT(collation='utf8_bin'),
               existing_nullable=True)
    op.alter_column('response', 'post_test_agents',
               existing_type=sa.Text(),
               type_=mysql.TEXT(collation='utf8_bin'),
               existing_nullable=True)
    # ### end Alembic commands ###
