"""empty message

Revision ID: fc015c6f4fd5
Revises: 4ca12d1b238d
Create Date: 2020-04-22 12:19:00.092690

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc015c6f4fd5'
down_revision = '4ca12d1b238d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response', sa.Column('pretest_reactions2', mysql.MEDIUMTEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('response', 'pretest_reactions2')
    # ### end Alembic commands ###
